name: CI Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    name: Build and Push Backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4 to support Node.js 20

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Updated to v3 to support Node.js 20
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Updated to v3 to support Node.js 20
      
      - name: Build the backend Docker image
        run: |
          docker build --progress=plain -t maboni82/homeassistant-tracker-backend:latest ./backend
       
      - name: Push the backend Docker image to Docker Hub
        run: |
          docker push maboni82/homeassistant-tracker-backend:latest

  build-frontend:
    runs-on: ubuntu-latest
    name: Build and Push Frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4 to support Node.js 20

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Updated to v3 to support Node.js 20
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Updated to v3 to support Node.js 20

      - name: Build the frontend Docker image
        run: |
          docker build --progress=plain -t maboni82/homeassistant-tracker-frontend:latest ./frontend
       
      - name: Push the frontend Docker image to Docker Hub
        run: |
          docker push maboni82/homeassistant-tracker-frontend:latest
