name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [backend, frontend]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set version-date tag
        id: tag
        run: |
          VERSION="v1.0.0"
          if [ ! -z "${{ github.event.release.tag_name }}" ]; then
            VERSION=${{ github.event.release.tag_name }}
          fi
          DATE_TAG=$(date +'%Y%m%d')
          VERSION_TAG="${VERSION}-${DATE_TAG}"
          echo "tag=${VERSION_TAG}" >> $GITHUB_ENV

      - name: Install dependencies (backend only)
        if: matrix.service == 'backend'
        run: |
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: false
          tags: |
            maboni82/homeassistant-tracker-${{ matrix.service }}:latest
            maboni82/homeassistant-tracker-${{ matrix.service }}:${{ env.tag }}
          builder: ${{ steps.buildx.outputs.name }}

      - name: Push Docker images to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            maboni82/homeassistant-tracker-${{ matrix.service }}:latest
            maboni82/homeassistant-tracker-${{ matrix.service }}:${{ env.tag }}
          builder: ${{ steps.buildx.outputs.name }}
